server:
  port: 6666
  context-path: /csi
spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/csi           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                                # 数据库连接密码
    filters: stat,wall,log4j
mybatis:
  mapperLocations: classpath:com/cqut/csi/mapper/*.xml
  typeAliasesPackage: com.cqut.model
management:
  security:
    enabled: false # 现在关闭系统的安全配置